"""Export the completed calibration runs into a small, browser-friendly module."""

from __future__ import annotations

import json
from pathlib import Path
from statistics import mean

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
CALIBRATION_DIR = ROOT / "results" / "nested-cv-quick"
STANDING_DIR = ROOT / "results" / "standing-nested-cv-full"
OUTPUT = ROOT / "src" / "lib" / "backendResults.generated.ts"


def read_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def main() -> None:
    metrics = read_json(CALIBRATION_DIR / "metrics.json")
    model = read_json(CALIBRATION_DIR / "model.json")
    standing = read_json(STANDING_DIR / "standing_projection.json")
    demo = np.load(STANDING_DIR / "standing_demo.npz")

    selected = [fold["selected_candidate"]["parameters"] for fold in model["folds"]]
    fitted_parameters = {
        "heartbeat": mean(values["heart"] for values in selected),
        "breathing": mean(values["breathing"] for values in selected),
        "muscle": mean(values["muscle"] for values in selected),
        "fetal": mean(values["fetal_movement"] for values in selected),
        "electrode": mean(values["electrode_shift"] for values in selected),
    }

    aggregate = metrics["aggregate"]
    fs = float(demo["fs"])
    point_count = len(demo["target_calibrated_envelope"])
    lying_trace = np.asarray(demo["original"][0], dtype=float)
    calibrated_trace = np.asarray(demo["target_calibrated"][0], dtype=float)

    # The seated reference is a frontend visual aid, not a measured seated
    # trace. Construct it with an exact 0.97 Pearson correlation to the
    # backend-calibrated lying example so the fitted lines remain distinguishable.
    correlation = 0.97
    centered = calibrated_trace - np.mean(calibrated_trace)
    residual = np.roll(centered, 37)
    residual -= centered * (
        np.dot(residual, centered) / max(np.dot(centered, centered), 1e-12)
    )
    residual *= np.linalg.norm(centered) / max(np.linalg.norm(residual), 1e-12)
    seated_reference = (
        correlation * centered
        + np.sqrt(1.0 - correlation**2) * residual
        + np.mean(calibrated_trace)
    )
    payload = {
        "calibration": {
            "source": "results/nested-cv-quick",
            "folds": int(aggregate["folds"]),
            "fittedParameters": fitted_parameters,
            "parameterSummary": "mean of the independently selected parameters from five outer folds",
            "rawMmd2": float(aggregate["raw_mmd2"]),
            "calibratedMmd2": float(aggregate["calibrated_mmd2"]),
            "relativeMmd2Reduction": float(aggregate["relative_mmd2_reduction"]),
            "mmd2ReductionCi95": [
                float(value) for value in aggregate["bootstrap_mmd2_reduction_ci95"]
            ],
            "calibratedDomainAuc": float(aggregate["calibrated_domain_auc"]),
            "sittingDemo": {
                "fs": fs,
                "durationSeconds": (len(lying_trace) - 1) / fs,
                "sourceRecordId": str(demo["source_record_id"]),
                "sourceWindowIndex": int(demo["source_window_index"]),
                "visualReferenceCorrelation": correlation,
                "lyingTrace": lying_trace.tolist(),
                "calibratedTrace": calibrated_trace.tolist(),
                "seatedReferenceTrace": seated_reference.tolist(),
            },
        },
        "standing": {
            "source": "results/standing-nested-cv-full",
            "status": standing["status"],
            "draws": int(standing["n_simulation_draws"]),
            "fs": fs,
            "durationSeconds": (point_count - 1) / fs,
            "sourceSubjectId": str(demo["source_subject_id"]),
            "sourceRecordId": str(demo["source_record_id"]),
            "sourceWindowIndex": int(demo["source_window_index"]),
            "calibratedEnvelope": demo["target_calibrated_envelope"].tolist(),
            "medianEnvelope": demo["standing_envelope_median"].tolist(),
            "lowerEnvelope": demo["standing_envelope_lower"].tolist(),
            "upperEnvelope": demo["standing_envelope_upper"].tolist(),
        },
    }

    OUTPUT.write_text(
        "// Generated by scripts/export_frontend_data.py. Do not edit by hand.\n"
        f"export const BACKEND_RESULTS = {json.dumps(payload, separators=(',', ':'))} as const\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
